# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('image_url', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=16)),
                ('date_time', models.DateTimeField()),
                ('keywords', models.CharField(max_length=64)),
                ('original_link', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('reading_number', models.IntegerField()),
                ('agree_number', models.IntegerField()),
                ('disagree_number', models.IntegerField()),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
