# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password_hash', models.CharField(max_length=64)),
                ('join_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
