# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20151214_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=32, primary_key=True, serialize=False),
        ),
    ]
